import Header from '@/components/Header/Header';
import Footer from '@/components/footer/Footer';
import '@/style/globals.css';
import localFont from '@next/font/local';
import { Inter, Mulish } from 'next/font/google';
import { Flip, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const mulish = Mulish({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mulish',
});

const LDRKaet = localFont({
  src: '../../public/fonts/ldr_kaet.ttf',
  variable: '--font-LDRKaet',
});

export const metadata = {
  title: {
    template: '%s | Teddies vs Monsters',
    default: 'Teddies vs Monsters',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const customToastStyle = {
    backgroundColor: '#CE8C3D',
    color: '#fff',
    background: '#CE8C3D',
    top: '50px',

    // Add any other custom styles you want to override here
  };
  return (
    <html
      lang='en'
      className={`${inter.variable} ${mulish.variable} ${LDRKaet.variable}`}
    >
      <body>
        <ToastContainer
          transition={Flip}
          hideProgressBar={false}
          position='top-center'
          autoClose={3000}
          newestOnTop={false}
          closeOnClick={true}
          rtl={false}
          draggable={true}
          pauseOnHover={true}
          theme='colored'
          toastStyle={customToastStyle}
        />
        <Header />
        <div className='mt-20 max-w-[1800px] mx-auto min-w-[350px]'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
